function [  ] = hitMissPlot( trace, level )
% plot hits and misses as 3D plot
% IN: trace struct containing all configurations
        % level 1 = L2i, 2 = L1d, 3 = L2

All_2way              =       getValues(trace.All_2way);
All_4way              =       getValues(trace.All_4way);
All_FA                =       getValues(trace.All_FA);
All_small             =       getValues(trace.All_small);
default               =       getValues(trace.default);
L1_2way               =       getValues(trace.L1_2way);
L1_8way               =       getValues(trace.L1_8way);
L1_small_4way         =       getValues(trace.L1_small_4way);
L1_small              =       getValues(trace.L1_small);

if level == 1
    % format data to plot
    hm = [  All_2way.L1iVChit, All_2way.L1imiss, All_2way.L1ihits; ...
            All_4way.L1iVChit, All_4way.L1imiss, All_4way.L1ihits; ...
            All_FA.L1iVChit, All_FA.L1imiss, All_FA.L1ihits; ...
            All_small.L1iVChit, All_small.L1imiss, All_small.L1ihits; ...
            default.L1iVChit, default.L1imiss, default.L1ihits; ...
            L1_2way.L1iVChit, L1_2way.L1imiss, L1_2way.L1ihits; ...
            L1_8way.L1iVChit, L1_8way.L1imiss, L1_8way.L1ihits; ...
            L1_small_4way.L1iVChit, L1_small_4way.L1imiss, L1_small_4way.L1ihits; ...
            L1_small.L1iVChit, L1_small.L1imiss, L1_small.L1ihits;];
else if level == 2
             hm = [  All_2way.L1dVChit, All_2way.L1dmiss, All_2way.L1dhits; ...
            All_4way.L1dVChit, All_4way.L1dmiss, All_4way.L1dhits; ...
            All_FA.L1dVChit, All_FA.L1dmiss, All_FA.L1dhits; ...
            All_small.L1dVChit, All_small.L1dmiss, All_small.L1dhits; ...
            default.L1dVChit, default.L1dmiss, default.L1dhits; ...
            L1_2way.L1dVChit, L1_2way.L1dmiss, L1_2way.L1dhits; ...
            L1_8way.L1dVChit, L1_8way.L1dmiss, L1_8way.L1dhits; ...
            L1_small_4way.L1dVChit, L1_small_4way.L1dmiss, L1_small_4way.L1dhits; ...
            L1_small.L1dVChit, L1_small.L1dmiss, L1_small.L1dhits;];
    else
        hm = [  All_2way.L2VChit, All_2way.L2miss, All_2way.L2hits; ...
            All_4way.L2VChit, All_4way.L2miss, All_4way.L2hits; ...
            All_FA.L2VChit, All_FA.L2miss, All_FA.L2hits; ...
            All_small.L2VChit, All_small.L2miss, All_small.L2hits; ...
            default.L2VChit, default.L2miss, default.L2hits; ...
            L1_2way.L2VChit, L1_2way.L2miss, L1_2way.L2hits; ...
            L1_8way.L2VChit, L1_8way.L2miss, L1_8way.L2hits; ...
            L1_small_4way.L2VChit, L1_small_4way.L2miss, L1_small_4way.L2hits; ...
            L1_small.L2VChit, L1_small.L2miss, L1_small.L2hits;];
    end
end
    

% log scale for data
hm = log10(hm);

% sort before plotting
% [sorhm,ind] = sortrows(hm);
       
% sort labels
lbls = {'All-2way', 'All-4way', 'All-FA', 'All-small', 'default-', ...
         'L1-2way', 'L1-8way', 'L1-small-4way', 'L1-small'};
% lbls = lbls(ind);

% 3D bar plot
bar3(hm);
set(gca,'YTickLabel',lbls);
if level == 1
    set(gca,'XTickLabel',{'L1i VC hit', 'L1i miss', 'L1i hit'});
    title(['L1i hit/miss count: ' trace.name]);
else if level == 2
        set(gca,'XTickLabel',{'L1d VC hit', 'L1d miss', 'L1d hit'});
        title(['L1d hit/miss count: ' trace.name]);
    else
        set(gca,'XTickLabel',{'L2 VC hit', 'L2 miss', 'L2 hit'});
        title(['L2 hit/miss count: ' trace.name]);
    end
end
zlabel('log_{10} scale');
grid on;

end