function [  ] = kickoutPlot( trace )
% plot kickouts and dirty kickouts
% IN: trace struct containing all configurations

All_2way              =       getValues(trace.All_2way);
All_4way              =       getValues(trace.All_4way);
All_FA                =       getValues(trace.All_FA);
All_small             =       getValues(trace.All_small);
default               =       getValues(trace.default);
L1_2way               =       getValues(trace.L1_2way);
L1_8way               =       getValues(trace.L1_8way);
L1_small_4way         =       getValues(trace.L1_small_4way);
L1_small              =       getValues(trace.L1_small);

% format data to plot
[kick,ind] = sortrows([
                    All_2way.L1iKicks, All_4way.L1iKicks, All_FA.L1iKicks, ... 
                    All_small.L1iKicks, default.L1iKicks, L1_2way.L1iKicks, ...
                    L1_8way.L1iKicks, L1_small_4way.L1iKicks, L1_small.L1iKicks; ...
                    All_2way.L1dKicks, All_4way.L1dKicks, All_FA.L1dKicks, ... 
                    All_small.L1dKicks, default.L1dKicks, L1_2way.L1dKicks, ...
                    L1_8way.L1dKicks, L1_small_4way.L1dKicks, L1_small.L1dKicks; ...
                    All_2way.L2Kicks, All_4way.L2Kicks, All_FA.L2Kicks, ... 
                    All_small.L2Kicks, default.L2Kicks, L1_2way.L2Kicks, ...
                    L1_8way.L2Kicks, L1_small_4way.L2Kicks, L1_small.L2Kicks; ...
                    All_2way.L1dDrtyKcks, All_4way.L1dDrtyKcks, All_FA.L1dDrtyKcks, ... 
                    All_small.L1dDrtyKcks, default.L1dDrtyKcks, L1_2way.L1dDrtyKcks, ...
                    L1_8way.L1dDrtyKcks, L1_small_4way.L1dDrtyKcks, L1_small.L1dDrtyKcks; ...
                    All_2way.L2DrtyKcks, All_4way.L2DrtyKcks, All_FA.L2DrtyKcks, ... 
                    All_small.L2DrtyKcks, default.L2DrtyKcks, L1_2way.L2DrtyKcks, ...
                    L1_8way.L2DrtyKcks, L1_small_4way.L2DrtyKcks, L1_small.L2DrtyKcks; ... 
                    ]'); 

% scale data
% kick = log10(kick);

% sort labels
lbls = {'All-2way', 'All-4way', 'All-FA', 'All-small', 'default-', ...
         'L1-2way', 'L1-8way', 'L1-small-4way', 'L1-small'};
lbls = lbls(ind);

% plot
bar(kick,'stacked');
set(gca,'XTickLabel',lbls);
xticklabel_rotate([],45,[],'Fontsize',12);
legend('L1i kickouts', 'L1d kickouts', 'L2 kickouts', 'L1d Dirty Kickouts', 'L2 Dirty Kickouts');
grid on;
title(['Kickouts: ' trace.name]);

end